import argparse
import os
import re


def prefixed_output_name(prefix, filename):
    text = str(prefix or "").strip()
    if not text:
        return filename
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", text).strip("._-")
    if not safe:
        return filename
    return f"{safe}_{filename}"


def cleanup_prefixed_outputs(outdir, prefix, subdirs=None):
    """Remove files generated by previous runs with the same output prefix."""
    text = str(prefix or "").strip()
    if not text:
        return 0
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", text).strip("._-")
    if not safe:
        return 0

    removed = 0
    roots = [outdir]
    for sub in (subdirs or []):
        roots.append(os.path.join(outdir, sub))

    for root in roots:
        if not os.path.isdir(root):
            continue
        for name in os.listdir(root):
            if not name.startswith(f"{safe}_"):
                continue
            path = os.path.join(root, name)
            if not os.path.isfile(path):
                continue
            try:
                os.remove(path)
                removed += 1
            except OSError:
                pass
    return removed


def build_cli_parser():
    ap = argparse.ArgumentParser(description="Analyze docking SDF plus interaction counts and generate a molecule-level report.")
    ap.add_argument("-i", "--input", required=True, help="Input SDF file")
    ap.add_argument("-o", "--outdir", default="rgroup_report", help="Output directory")
    ap.add_argument("-f", "--file-prefix", default="", help="Optional prefix applied to output filenames so multiple runs can share one output directory")
    ap.add_argument("-c", "--interaction-csv", default="direct_linker_filtered.csv", help="CSV with interaction_count by ligand ID (Title column)")
    ap.add_argument("-j", "--interaction-id-col", default="Title", help="Ligand ID column name in interaction CSV")
    ap.add_argument("-k", "--interaction-count-col", default="interaction_count", help="Interaction count column in interaction CSV")
    ap.add_argument("-d", "--id-prop", default=None, help="Preferred SD tag for molecule identifier")
    ap.add_argument(
        "-s", "--score-props",
        nargs="*",
        default=["r_i_docking_score", "r_i_glide_gscore", "glide_gscore", "docking_score", "score", "DockingScore"],
        help="Candidate SD tags for docking score (lower is better)",
    )
    ap.add_argument("-a", "--auto-detect-score", action="store_true", help="Auto-detect additional score-like SD tags")
    ap.add_argument("-l", "--cluster-prop", default=None, help="Optional SD tag containing a cluster ID")
    ap.add_argument("-g", "--min-group-size", type=int, default=1, help="Deprecated: retained for backward CLI compatibility")
    ap.add_argument("-t", "--top-per-scaffold", type=int, default=1, help="Deprecated: retained for backward CLI compatibility")
    ap.add_argument("-m", "--max-scaffolds-in-report", type=int, default=0, help="Deprecated: retained for backward CLI compatibility")
    ap.add_argument(
        "-P", "--protein-pdb",
        default=None,
        help=(
            "Optional receptor structure file(s) (.pdb, .cif/.mmcif, or .mol2). "
            "Pass multiple files as a comma-separated list in one flag, for example --protein-pdb a.pdb,b.pdb. "
            "Format is auto-detected from extension and used by the hover docking viewer. "
            "For MOL2 inputs, secondary structure is computed with MDTraj DSSP."
        ),
    )
    ap.add_argument(
        "-r", "--ref-ligand-sdf",
        default=None,
        help=(
            "Optional SDF file with one or more reference / crystal ligands (3D coordinates). "
            "Each entry is shown as a 2D-image tile in a 'Reference Ligands' panel above Molecule List. "
            "The mol block title line is used as the ligand name. "
            "A 'View Pose' button opens the 3D viewer for that ligand; an overlay checkbox lets you "
            "include it alongside docking-pose overlays."
        ),
    )
    ap.add_argument(
        "-w", "--max-molecular-weight",
        type=float,
        default=None,
        help="Maximum molecular weight for report-facing outputs (omit to disable filter)",
    )
    ap.add_argument(
        "-b", "--max-rotatable-bonds",
        type=float,
        default=None,
        help="Maximum rotatable bonds for report-facing outputs (omit to disable filter)",
    )
    ap.add_argument(
        "-D", "--max-hbond-donors",
        type=float,
        default=None,
        help="Maximum hydrogen bond donors for report-facing outputs (omit to disable filter)",
    )
    ap.add_argument(
        "-A", "--max-hbond-acceptors",
        type=float,
        default=None,
        help="Maximum hydrogen bond acceptors for report-facing outputs (omit to disable filter)",
    )
    ap.add_argument(
        "-e", "--exclude-smiles-file",
        default=None,
        help="Optional text file (one SMILES/motif per line) to exclude molecules by substructure match (e.g., phenol, urea).",
    )
    ap.add_argument(
        "-G", "--generate-all-mol-images",
        action="store_true",
        help=(
            "Generate base64 PNG for every molecule during SDF parsing. "
            "Disabled by default for faster runs; report images are generated lazily for displayed molecules."
        ),
    )
    ap.add_argument(
        "--use-first-molecule-template",
        action="store_true",
        help=(
            "Use the first valid molecule in the input SDF as a 2D depiction template for all molecules. "
            "When enabled, the report run writes macrocycle-friendly 2D PNG depictions to the figures folder "
            "using template-matched orientation where possible."
        ),
    )
    ap.add_argument(
        "--torsion-smarts",
        default=None,
        help=(
            "Optional SMARTS pattern defining exactly four atoms for a torsion angle. "
            "When provided, the report computes one torsion per molecule using the first SMARTS match "
            "and exposes it in the Molecule Properties filters and plots."
        ),
    )
    ap.add_argument(
        "--torsion-label",
        default="Torsion (deg)",
        help="Display label for the optional torsion property in the HTML report.",
    )
    ap.add_argument(
        "-n", "--n-workers",
        type=int,
        default=0,
        help=(
            "Number of worker processes (0=auto-detect from CPU count). "
            "Controls parallelism for SDF parsing, ranking, and report generation. "
            "Set to 1 to disable parallelism entirely."
        ),
    )
    return ap


def initialize_output_layout(outdir, file_prefix):
    os.makedirs(outdir, exist_ok=True)
    fig_dir = os.path.join(outdir, "figures")
    os.makedirs(fig_dir, exist_ok=True)

    removed_prefixed = cleanup_prefixed_outputs(
        outdir,
        file_prefix,
        subdirs=["figures"],
    )

    return {
        "fig_dir": fig_dir,
        "removed_prefixed": removed_prefixed,
        "report_filename": prefixed_output_name(file_prefix, "report.html"),
        "molecule_summary_name": prefixed_output_name(file_prefix, "molecule_summary.csv"),
        "qc_summary_name": prefixed_output_name(file_prefix, "qc_summary.csv"),
        "manifest_name": prefixed_output_name(file_prefix, "run_manifest.json"),
    }


def auto_detect_score_props(sample_props):
    preferred = [
        "r_i_docking_score",
        "r_i_glide_gscore",
        "glide_gscore",
        "docking_score",
        "score",
    ]
    found = [prop for prop in preferred if prop in sample_props]
    if found:
        return found

    hits = [prop for prop in sample_props if re.search(r"score|gscore|docking", prop, re.IGNORECASE)]
    return sorted(hits)


def resolve_score_props(suppl, total_mols, base_score_props, auto_detect_score):
    score_props = list(base_score_props)
    if auto_detect_score:
        all_prop_names_scan: set = set()
        for index in range(total_mols):
            mol = suppl[index]
            if mol is not None:
                for prop in mol.GetPropNames():
                    all_prop_names_scan.add(prop)
        for prop in auto_detect_score_props(all_prop_names_scan):
            if prop not in score_props:
                score_props.append(prop)
    return score_props